autor = 'Machado de Assis'
print(autor.upper())
print(autor.lower())
print(autor.isalpha())
print(autor.startswith('M'))
print(autor.startswith('m'))
print(autor.lower().startswith('m'))
print(autor.endswith('Assis'))
print('Joaquim Maria' + ' ' + autor)
print(autor[0])
print(autor[2])
print(autor[-1])
print(autor[-2])
print(autor[11:])
print(autor[:2])
print(autor[:-1])
print(autor[8:-6])
